### ISSUE TITLE
每日番剧指令报错

### ISSUE THREAD

**Issue by X-Zero-L** [benx1n/everyday-bangumi#2]
![I%KXAM08L) V(B{HU 21WR](https://user-images.githubusercontent.com/98764734/178534059-5a1d6b12-7097-46ef-98a9-8e5863683ba3.png)
![%RI%@HX)2)J1ZQ`1(CS(9%9](https://user-images.githubusercontent.com/98764734/178534082-a5aaac6e-f748-4956-bee4-ec2ec40777f0.png)

**Comment by benx1n** [comment]
如果有其他插件修改了windows的默认事件循环策略，就会引起playwright的报错
目前已知的可能有使用了aiohttp的插件比如setu_renew
详情可以看这里[issue#1](https://github.com/benx1n/hoshinobot-plugin-ddcheck/issues/1#issuecomment-1119224861)
