### ISSUE TITLE
TypeError: 'PosixPath' object is not iterable

### ISSUE THREAD

**Issue by Ayusummer** [benx1n/everyday-bangumi#4]
![image](https://user-images.githubusercontent.com/59549826/182192933-ddd72014-42e3-466b-b572-73e68d462e28.png)

系统版本: ubuntu20.04LTS
python版本:3.9.1
jinja2版本: 2.10
nonebot版本:1.8.0

怀疑可能是 jinja2 的问题, 目前 hoshino 只支持 2.11.2 以下的 jinja2

![image](https://user-images.githubusercontent.com/59549826/182193973-06b30bc1-674d-4035-8f52-97a24e2aa490.png)

**Comment by benx1n** [comment]
可能是jinja2版本有点低了？hoshino与jinja2 3.X版本可以兼容，升级一下依赖试试

**Comment by Ayusummer** [comment]
好滴, 我试试😋
